steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-central1-docker.pkg.dev/gcp101713-michalpiasecki/my-repository/quickstart-image:tag1 .
  automapSubstitutions: true
images:
- 'us-central1-docker.pkg.dev/gcp101713-michalpiasecki/my-repository/quickstart-image:tag1'
