apiVersion: v1
kind: Pod
metadata:
  name: devwebapp
  labels:
    app: devwebapp
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: 'update'
    vault.hashicorp.com/role: "devweb-app"
    vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/data/devwebapp/config"
    # path is: /vault/secret/credentials.txt
    vault.hashicorp.com/agent-inject-template-credentials2.txt: |
       {{- with secret "secret/data/devwebapp/config" -}}
       {{ .Data.data.username }}:{{ .Data.data.password }}
       {{- end -}}
spec:
  serviceAccountName: internal-app
  containers:
    - name: devwebapp
      image: jweissig/app:0.0.1